# 14. Lecture 7. Recommender Systems

At the end of this lecture, you will be able to

* understand the problem definition and assumptions of recommender systems

* understand the impact of similarity measures in the K-Nearest Neighbor method

* understand the need to impose the low rank assumption in collaborative filtering

* iteratively find values of  and  (given ) in collaborative filtering

## 7.2 Introduction

* problem definition
* K-Nearest algorithm KNN
* Matrix factorization (collaborative filtering)

Ex: Netflix recommendation

n users, m movies: matrix  
$ Y_n,m $

.5 millions users, 18000 movies: Sparse matrix

approach 1: features and linear regression
issue: get the features
issue: need enought data point 

approach 2: find similar users



## 7.3 K-Nearest Neighbor Method

$ \hat{Y}_ai = 1/K* \sum_{KNN} Y_{bi} $

with average

Compute the similarity (euclidien, other)

$ \hat{Y}_ai = 1/K* \sum_{KNN} * Sim * Y_{bi} $

with weighted average using similarity

Deviation from the average score

Different euristics

## 7.4 Collaborative Filtering: the naive approach

Input matrix  Y (recommendations only)  
Output matrix  X (full)

$$ J(X) = \sum_{(a,i) \in D} (Y_{ai} - X_{ai}^2/2) + \lambda/2 \sum_{(a,i)} X_{ai}^2
$$

Differentiate: 

For $ (a,i) \in D $:  
$$ {\partial J \over \partial X_{ai}} = (1+ \lambda) * X_{ai} - Y_{ai} $$

For $ (a,i) \notin D $:  
$$ {\partial J \over \partial X_{ai}} = \lambda * X_{ai} $$

Solve = 0:

For $ (a,i) \in D $:  
$$ X_{ai} = Y_{ai} / (1+ \lambda) = 0 $$


For $ (a,i) \notin D $:  
$$ X_{ai} = \lambda * X_{ai} = 0 $$

## 7.5 Collaborative Filtering with Matrix Factorization

Assumption: X is low rank

Rank: Factorize
D( n * m )  parameters > n + m

rank 1: 

$ X = UV^T $ 

> Matrix Rank  
> for some $nxd$ matrix $U$ and $dxm$ matrix $V^T$. The number d is the rank of the matrix X.

rank 2: 

$$
\begin{bmatrix} 1 & 2 \\ .. & .. \\ .. & .. \end{bmatrix}
\cdot
\begin{bmatrix} 3 & 4 & 5 \\ .. & .. & .. \end{bmatrix}
 $$
with:  
$$
\begin{bmatrix} 1 & 2 \\ .. & .. \\ .. & .. \end{bmatrix}
\begin{matrix} \rarr user_1 \\ \rarr user_2 \\ \rarr user_3 \end{matrix}
$$
and
$$
\begin{bmatrix} 3 & 4 & 5 \\ .. & .. & .. \end{bmatrix}\\
\begin{matrix} movie_1 & 4 & 5 \end{matrix}
 $$

## 7.6 Alternating Minimization

Convergenace? Local optimal

Find $U$ and $V$ that minimize this objective function:

$$
J = \sum_{(a,i) \in D}{(Y_{ai} - UV^T_{ai})^2 \over 2} + {\lambda \over 2}(\sum U^2 + \sum V^2)
$$

 
To simplify the problem, we fix $U$ and solve for $V$, then fix $V$ to be the result from the previous step and solve for $U$, and repeat this alternate process until we find the solution.

### 7.6.Q2

$$ Y = \begin{bmatrix} 1 & 8 & ? \\ 2 & ? & 5 \end{bmatrix}$$  
  
$$ U = \begin{bmatrix} u_1 \\ u_2 \end{bmatrix} and \ \  V^T = \begin{bmatrix} 4 & 2 & 1 \end{bmatrix}$$
  
$$ X = \begin{bmatrix} 4*u_1 & 2*u_1 & 1*u_1 \\ 4*u_2 & 2*u_2 & 1*u_2 \end{bmatrix}$$

wolfram: derivative of (1-4x)^2/2 + (8-2x)^2/2 + lambda/2*x^2

In [7]:
import numpy as np
U = np.array([6,0,3,6]).reshape(4,1)
V = np.array([4,2,1]).reshape(3,1)
print(U, V)

[[6]
 [0]
 [3]
 [6]] [[4]
 [2]
 [1]]


In [31]:
X = U*V.T
print(X)

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


In [32]:
Y = np.array([5., np.nan, 7, np.nan, 2, np.nan, 4, np.nan, np.nan, np.nan, 3, 6]).reshape(4,3)
print(Y)

[[ 5. nan  7.]
 [nan  2. nan]
 [ 4. nan nan]
 [nan  3.  6.]]


In [14]:
np.sum( (Y - X)**2 ) / 2

nan