# 21. Homework 3. Neural Networks

## 1. Neural Netweoks

In this problem we will analyze a simple neural network to understand its classification properties. Consider the neural network given in the figure below, with ReLU activation functions (denoted by $f$) on all neurons, and a softmax activation function in the output layer:

![img](img/images_hw4_p1.png)

### 1. Q1


In [1]:
import numpy as np
import math

X = np.array([3.,14,1], dtype=np.float64).reshape([1,3])
W = np.array([1,0,-1,0,1,-1,-1,0,-1,0,-1,-1], dtype=np.float64).reshape([4,3])
V = np.array([1,1,1,1,0,-1,-1,-1,-1,2],dtype=np.float64).reshape([2,5])

print(X, W, V, sep='\n')

def ReLU(x):
    return max(x, 0)

Z = X @ W.T 
print("Z: ", Z)

F = np.vectorize(ReLU)(X @ W.T)
print("F: ", F)

F2 = np.c_[ F, np.ones(F.shape[0])]

U = F2 @ V.T
print(U)

FU = np.vectorize(ReLU)(U)
print(FU)

[[ 3. 14.  1.]]
[[ 1.  0. -1.]
 [ 0.  1. -1.]
 [-1.  0. -1.]
 [ 0. -1. -1.]]
[[ 1.  1.  1.  1.  0.]
 [-1. -1. -1. -1.  2.]]
Z:  [[  2.  13.  -4. -15.]]
F:  [[ 2. 13.  0.  0.]]
[[ 15. -13.]]
[[15.  0.]]


In [2]:
# X = np.array([3.,14,1], dtype=np.float64).reshape([1,3])
# Y = np.array([3.,14,1], dtype=np.float64).reshape([3,1])

# print(X)
# print(Y)

In [3]:
from math import exp

def o(u1, u2):
    return exp(u1) / (exp(u1) + exp(u2))

# print("o1", o(15, 0))
# print("o2", o(0, 15))

### 1. Q2

In [4]:
# print(o(1,1))
# print(o(0,2))
# print(o(3,0))


In [5]:
def oo(u1,u2,beta):
    return exp( beta * ReLU(u1)) / ( exp( beta * ReLU(u1)) + exp( beta * ReLU(u2)))

## 2. LSTM

A Sigmoid function is a function with a S shaped curve

In ML, the term "sigmoid fuction" is an alias fro the logistics function.

$$ sigmoid(x) = { 1 \over (1 + e^{-x}) } $$
$$ = { e^x \over (e^x + 1) } $$


Sources:
* [Sigmoid - Wikipedia](https://en.wikipedia.org/wiki/Sigmoid_function)

In [6]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

# print(0, sigmoid(0))
# print(-1, sigmoid(-1))


In [7]:
def tanh(x):
    return((math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x)))

$$ f_t = sigmoid(W^{f,h}h_{t-1} + W^{f,x}x_{t} + b_f) $$


In [8]:
W_fh = 0.
W_ih = 0.
W_oh = 0
W_fx = 0.
W_ix = 100.
W_ox = 100
b_f = -100.
b_i = 100.
b_o = 0
W_ch = -100.
W_cx = 50
b_c = 0

In [5]:
nsteps = 6

h = [None] * (nsteps + 1)
h[-1] = 0

c = [None] * (nsteps + 1)
c[-1] = 0

x = [0.] * (nsteps + 1)

print(h)

[None, None, None, None, None, None, 0]


In [10]:
def forget_gate(t, h, x, W_fh=W_fh, W_fx=W_fx, b_f=b_f):
    return sigmoid(W_fh * h[t-1] + W_fx * x[t] + b_f)

$$ i_t = sigmoid(W^{i,h}h_{t-1} + W^{i,x}x_{t} + b_i) $$

In [11]:
def input_gate(t, h, x, W_ih=W_ih, W_ix=W_ix, b_i=b_i):
    return sigmoid(W_ih * h[t-1] + W_ix * x[t] + b_i)


$$ o_t = sigmoid(W^{o,h}h_{t-1} + W^{o,x}x_{t} + b_o) $$

In [12]:
def output_gate(t, h, x, W_oh=W_oh, W_ox=W_ox, b_o=b_o):
    return sigmoid(W_oh * h[t-1] + W_ox * x[t] + b_o)

$$ c_t = f_t \odot c_{t-1} + i_t \odot tanh(W^{c,h}h_{t-1} + W^{c,x}x_{t} + b_c) $$

In [13]:
def cell(t, h, x, W_ch=W_ch, W_cx=W_cx, b_c=b_c):
    return forget_gate(t, h, x) * c[t-1] + input_gate(t, h, x) * tanh(W_ch * h[t-1] + W_cx * x[t] + b_c)

In [14]:
# print(round(0.5))
# print(round(-0.5))

def h_state(t, h, x):
    return round(output_gate(t, h, x) * tanh(cell(t, h, x)))

In [4]:
def learn():
    for t in range(nsteps):

        c[t] = cell(t, h, x)
        h[t] = h_state(t, h, x)
        
    print("h", h[:nsteps+1])

# learn()

In [3]:
# print("h", h[:6])

In [2]:
# nsteps = 10

# h = [None] * (nsteps + 1)
# h[-1] = 0

# print(h)

# c = [None] * (nsteps + 1)
# c[-1] = 0

# x = [0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]

# for t in range(nsteps):

#     c[t] = cell(t, h, x)
#     h[t] = h_state(t, h, x)
    
# print("h", h[:nsteps+1])

## 3. Backpropagation

One of the key steps for training multi-layer neural networks is stochastic gradient descent. We will use the back-propagation algorithm to compute the gradient of the loss function with respect to the model parameters.

Consider the $L$-layer neural network below:



## 4. Words embeddings

* [ ] The first network cannot classify the sequence correctly
* [ ] The second network cannot classify the sequence correctly
* [ ] The second network has a fighting chance at classifying the sequence
* [ ] The first network has a fighting chance at classifying the sequence

https://towardsdatascience.com/neural-network-embeddings-explained-4d028e6f0526 

Embedding: a method used to {represent|map} a {discrete|categorical} variables as a vector of continuous numbers.
Low dimension, learn 
Reduce dimensionality

3 purposes:
- find nearest neighbors
- as input to a machine learning model for a supervised task
- for visualization of concepts and relations between categories

Overcome limitation of one-hot encoding
Drawbacks:
- size of the matrix (1 dim per category)
- mapping contains no meaning

embedding NN + supervised task (train with data)


