# 21. Homework 3. Neural Networks

## 1. Neural Netweoks

In this problem we will analyze a simple neural network to understand its classification properties. Consider the neural network given in the figure below, with ReLU activation functions (denoted by $f$) on all neurons, and a softmax activation function in the output layer:

![img](img/images_hw4_p1.png)

### 1. Q1


In [21]:
import numpy as np
import math

X = np.array([3.,14,1], dtype=np.float64).reshape([1,3])
W = np.array([1,0,-1,0,1,-1,-1,0,-1,0,-1,-1], dtype=np.float64).reshape([4,3])
V = np.array([1,1,1,1,0,-1,-1,-1,-1,2],dtype=np.float64).reshape([2,5])

print(X, W, V, sep='\n')

def ReLU(x):
    return max(x, 0)

Z = X @ W.T 
print("Z: ", Z)

F = np.vectorize(ReLU)(X @ W.T)
print("F: ", F)

F2 = np.c_[ F, np.ones(F.shape[0])]

U = F2 @ V.T
print(U)

FU = np.vectorize(ReLU)(U)
print(FU)

[[ 3. 14.  1.]]
[[ 1.  0. -1.]
 [ 0.  1. -1.]
 [-1.  0. -1.]
 [ 0. -1. -1.]]
[[ 1.  1.  1.  1.  0.]
 [-1. -1. -1. -1.  2.]]
Z:  [[  2.  13.  -4. -15.]]
F:  [[ 2. 13.  0.  0.]]
[[ 15. -13.]]
[[15.  0.]]


In [26]:
# X = np.array([3.,14,1], dtype=np.float64).reshape([1,3])
# Y = np.array([3.,14,1], dtype=np.float64).reshape([3,1])

# print(X)
# print(Y)

In [25]:
from math import exp

def o(u1, u2):
    return exp(u1) / (exp(u1) + exp(u2))

# print("o1", o(15, 0))
# print("o2", o(0, 15))

### 1. Q2

In [24]:
# print(o(1,1))
# print(o(0,2))
# print(o(3,0))


In [23]:
def oo(u1,u2,beta):
    return exp( beta * ReLU(u1)) / ( exp( beta * ReLU(u1)) + exp( beta * ReLU(u2)))

## 2. LSTM

## 3. Backpropagation

## 4. Words embeddings

* [ ] The first network cannot classify the sequence correctly
* [ ] The second network cannot classify the sequence correctly
* [ ] The second network has a fighting chance at classifying the sequence
* [ ] The first network has a fighting chance at classifying the sequence

b, d incorrect (tested)  
a, b incorrect (..)  
c, d ??
