# 12. Unit 2. Lecture 5
## 4. Empirical Risk

In [3]:
import numpy as np

In [10]:
X = np.array([1,0,1,1,1,1,1,1,-1,-1,1,1])
X = X.reshape(4,3)
X

array([[ 1,  0,  1],
       [ 1,  1,  1],
       [ 1,  1, -1],
       [-1,  1,  1]])

In [11]:
y = np.array([2,2.7,-.7,2.]).reshape(4,1)
y

array([[ 2. ],
       [ 2.7],
       [-0.7],
       [ 2. ]])

In [14]:
theta = np.array([0,1,2]).reshape(3,1)
theta

array([[0],
       [1],
       [2]])

In [15]:
def Loss_h(z):
    if z >= 1:
        return 0
    else:
        return 1 - z

In [24]:
def Risk(theta, X, y, loss):
    observations, features = X.shape

    print("X", X)

    P = (y - np.dot(X, theta))
    print("P", P)

    H = np.vectorize(loss)(P)
    print("H", H)

    r = 1. / observations * np.sum(H)

    return r

Risk(theta, X, y, Loss_h)

X [[ 1  0  1]
 [ 1  1  1]
 [ 1  1 -1]
 [-1  1  1]]
P [[ 0. ]
 [-0.3]
 [ 0.3]
 [-1. ]]
H [[1. ]
 [1.3]
 [0.7]
 [2. ]]


1.25

In [25]:
def Loss_se(x):
    return x * x * .5

Risk(theta, X, y, Loss_se)

X [[ 1  0  1]
 [ 1  1  1]
 [ 1  1 -1]
 [-1  1  1]]
P [[ 0. ]
 [-0.3]
 [ 0.3]
 [-1. ]]
H [[0.   ]
 [0.045]
 [0.045]
 [0.5  ]]


0.1475