# 22. Lecture 12. Convolutional Neural Networks

## 12.1 Objectives

Convolutional neural networks (CNNs)

Objectives:
* Know the differences between feed-forward and Convolutional neural networks (CNNs).
* Implement the key parts in the CNNs, including **convolution**, **max pooling** units.
* Determine the dimension of each channel in different layers with a given CNNs.

## 12.2 Convolutional Neural Networks

Ojective: Image classification using NN

Key parts of CNN
* convolution
* pooling

### Limitations of FFNN
1. Problem 1: The size of the network (number of weights too high)
2. Problem 2: Learning would be too long. Examples are sensitive about the location (too many degree of freedom)

Example:
* For an 1000x1000px image
* An input layer of 1000x1000 units (same size)
* An hidden layer (1) of 1000x1000 units (same size)
* Fully connected mapping of (1000x1000) x (1000x1000) = 10^12 weights

### Method 1: Patch classifier/filter

A small patch, with few weights

Ex: 11x11 patch with 11x11 weights, giving 1 output

inner product if patch dot the filter
f = ReLU ( [] . [] )

Return higher value when filter meet a location which is "similar"

The weights are the same for all patches of image. the same set of weight.

Algorithm:
* move by x pixels (default 1)
* x is called stride

Exmaple of non-linearity:
- ReLU
- sigmoid
- (shrinkage function)
- ...  
  

Differences FFNN vs. CNN:
1. local connectivity
2. shared weights 



### Method 2: POOLING

Compressing the convoluted image or set of features
Using: a patch from image, a stride and a function, such as f = max{...}

Pooling paramrters:
* the dimension of the patch n x m
* the stride s
* the poolong function f

Example of pooling:
- Average Pooling
- L1
- L2
- Max Pooling
- Sum Pooling

![covolution and pooling](img/A-schematic-diagram-of-convolution-and-max-pooling-layer-In-the-convolution-layer-a.png)
![covolution and pooling](img/Schematic-representation-of-a-convolution-and-pooling-layer-in-a-CNN.png)

### 12.2.+ How to calculate convolution with python?

Using numpy: `convolve()`

In [7]:
import numpy as np 
x = [1, 1, 2, 0, 1]
y = [-1, 1]

print(np.convolve(x, y, mode ='full'))
print(np.convolve(y, x, mode ='full'))
print(np.convolve(x, y, mode ='same'))
print(np.convolve(y, x, mode ='same'))
print(np.convolve(x, y, mode ='valid'))

[-1  0 -1  2 -1  1]
[-1  0 -1  2 -1  1]
[-1  0 -1  2 -1]
[-1  0 -1  2 -1]
[ 0 -1  2 -1]


In [20]:
from scipy import signal
x = [1, 1, 2, 0, 1]
y = [-1, 1]

print(signal.convolve(x,y))

x = np.ones(16).reshape(4,4)
y = np.array([1,0,0,1]).reshape(2,2)
print(x, y, sep="\n")

print(signal.convolve(x,y, mode='full'))

print(signal.convolve2d(x,y, boundary='fill'))

[-1  0 -1  2 -1  1]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 0]
 [0 1]]
[[1. 1. 1. 1. 0.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [0. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 0.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [0. 1. 1. 1. 1.]]


In [42]:
f = [1,3,-1,1,-3]
g = [1,0,-1]
# g.reverse()
# g_ = list(reversed(g))
g_ = g[::-1]
print(g_)
# = g.reversed
np.convolve(f,g_,mode='same')

[-1, 0, 1]


array([-3,  2,  2,  2,  1])

In [49]:
f = np.array([1,2,1,2,1,1,1,1,1]).reshape(3,3)
g_ = np.array([1,0.5,0.5,1]).reshape(2,2)
print(f, g_)
g = np.fliplr(np.flipud(g_))
print(g)

c = signal.convolve(f,g, mode='valid')
print(c)

c.sum()


[[1 2 1]
 [2 1 1]
 [1 1 1]] [[1.  0.5]
 [0.5 1. ]]
[[1.  0.5]
 [0.5 1. ]]
[[4. 4.]
 [4. 3.]]


15.0

## 12.3 CNN (cont.)

How to construct a CNN

Layer 1:
- Multiple filter-maps aka. KERNEL (to indentify some features)

Layer 2:
- Pooling (to reduce the size of the images)

what are channels?

CNN's are architectures that combine these 2 types of layers successively (in a variety of different ways).

## 12.Extra

Convolution vs. Cross-Correlation



Conditions for image recognition

* spatial locality
* translation invariance

Are CNN are invariant to:
- translation, rotation and scaling ?
- illumination variation
- occlusion
- scale
- view point
- deformation



filters

Image > n 2D Filters > tensor of n channels (*) tensor filter

In [52]:
I = np.array([1,0,2,3,1,0,0,0,4]).reshape(3,3)
F = np.array([1,0,0,1]).reshape(2,2)

print(I)
print(F)

[[1 0 2]
 [3 1 0]
 [0 0 4]]
[[1 0]
 [0 1]]


In [61]:
import torch
import torch.nn.functional as F

input = torch.from_numpy(I)

NN = 

conv1 = torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=(3, 3), padding=1),
conv1_f = torch.nn.ReLU(),
pool1 = torch.nn.MaxPool2d(2, stride=1)

pool1(input)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        # Pass data through conv1
        # x = conv1(x)
        # Use the rectified-linear activation function over x
        x = F.relu(x)

        x = F.max_pool2d(x)


        # Run max pooling over x
        x = F.max_pool2d(x, 2)
        
        return x

NN.forward(input)

RuntimeError: non-empty 3D or 4D (batch mode) tensor expected for input