# 15. Unit 2. Homework 2

## 1. Collaborative Filtering, Kernels, Linear Regression

### 1.(a)

In [2]:
import numpy as np
U = np.array([6,0,3,6]).reshape(4,1)
V = np.array([4,2,1]).reshape(3,1)
print(U, V, sep="\n\n")

[[6]
 [0]
 [3]
 [6]]

[[4]
 [2]
 [1]]


In [3]:
X = U*V.T
print(X)

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


### 1.(b)

In [4]:
Y = np.array([5., np.nan, 7, np.nan, 2, np.nan, 4, np.nan, np.nan, np.nan, 3, 6]).reshape(4,3)
print(Y)

[[ 5. nan  7.]
 [nan  2. nan]
 [ 4. nan nan]
 [nan  3.  6.]]


In [9]:
np.sum( (Y - X)**2 ) / 2 # test

nan

In [6]:
n , m = X.shape
sum = 0

for N in range(n):
    for M in range(m):
        if ~np.isnan(Y[N][M]) and ~np.isnan(X[N][M]):
            print( "(" , Y[N][M], "-", X[N][M], ")^2 ", (Y[N][M] - X[N][M]) ** 2, end=" + ")
            sum += (Y[N][M] - X[N][M]) ** 2
sum /= 2

print(" / 2 = ", sum)

( 5.0 - 24 )^2  361.0 + ( 7.0 - 6 )^2  1.0 + ( 2.0 - 0 )^2  4.0 + ( 4.0 - 12 )^2  64.0 + ( 3.0 - 12 )^2  81.0 + ( 6.0 - 6 )^2  0.0 +  / 2 =  255.5


In [7]:
(np.sum(U**2)+np.sum(V**2))/2



51.0

### 1. (c)

$$
\begin{matrix}
X=UV^T & { \begin{bmatrix} 4 & 2 & 1 \end{bmatrix} } \\
{\begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \end{bmatrix}} & {\begin{bmatrix} 4*u_1 & 2*u_1 & 1*u_1 \\ 4*u_2 & 2*u_2 & 1*u_2 \\ 4*u_3 & 2*u_3 & 1*u_3 \\ 4*u_4 & 2*u_4 & 1*u_4 \end{bmatrix}}
\end{matrix}
$$

In [38]:
## u1

from sympy import *
import numpy as np
x, L = symbols('x L')
y = pow((1-4*x),2)/2 + pow((8-2*x),2)/2 + L/2*pow(x,2)
yprime = y.diff(x)
yprime

L*x + 20*x - 20

In [39]:
eq = Eq(yprime,0)
solution = solve(eq, x)
solution

[20/(L + 20)]

In [54]:
np.nansum(Y*V.T, axis=1).reshape(4,1)

array([[27.],
       [ 4.],
       [16.],
       [12.]])

In [66]:
np.nansum((Y*V.T)/(Y*V.T) * (V*V).T, axis=1).reshape(4,1)+1

array([[18.],
       [ 5.],
       [17.],
       [ 6.]])

In [73]:
def YuV(Y, V):
    num = np.nansum(Y*V.T, axis=1).reshape(4,1)
    denum = np.nansum((Y*V.T)/(Y*V.T) * (V*V).T, axis=1).reshape(4,1)+1
    return num, denum

solution = YuV(Y,V)

for i in range(4):
    print(solution[0][i] , solution[1][i])

[27.] [18.]
[4.] [5.]
[16.] [17.]
[12.] [6.]


## 2. Feature Vectors Transformation

### 2. (a)

## 3. Kernels

### 3. (a)

### 3 (b)

## 4. Kernels-II

### 4. (a)

1. 
[x] linear kernel 
[ ] quadratic kernel
[x] order 3 kernel
[x] RBF kernel

2. 
[x] linear kernel
[x] quadratic kernel
[x] order 3 kernel
[v] RBF kernel


3. 
[v] linear kernel
[x] quadratic kernel
[x] order 3 kernel
[x] RBF kernel

4. 
[x] linear kernel
[x] quadratic kernel
[ ] order 3 kernel
[x] RBF kernel


## 5. Linear Regression and Regularization


> 2*lambda*theta - 2*sum_t(y^{t}-theta*x^{t}-theta_0)*x^{t}

$$ {\partial L \over \partial\theta} = 2*\lambda*\theta - 2*\sum_t(y^{t}-\theta*x^{t}-\theta_0)*x^{t} $$

> -2*sum_t(y^{t}-theta*x^{t}-theta_0)

$$ {\partial L \over \partial\theta_0} = -2*\sum_t(y^{t}-\theta*x^{t}-\theta_0) $$

### 5. (c)

Find the closed form expression for $\theta$ and $\theta_0$ which solves the ridge regression minimization above.

Assume  is fixed, write down an expression for the optimal  in terms of .


1/ 
For the first part, take your solution for ${\partial L \over \partial\theta_0}$ from 5(b), set to zero, and solve for $\theta_0$.


= 1/n*sum_t(y^{t} - theta*x^{t})




2/
For the second part, take your solution for ${\partial L \over \partial\theta}$ from 5(b), replace $\theta_0$ with the first step from 5(c), set to zero, and solve for $--$. 


= (sum_t(x^{t}*y^{t})-sum_t(x^{t})*sum_t(y^{t}))/(lambda - barx*sum_t(x^{t})+sum_t((x^{t})^2))